apiVersion: v1
kind: Pod
metadata:
  name: logging
spec:
  containers:
  - name: ubuntu
    image: ubuntu:18.04
    command: ['/bin/bash', '-c', '--']
    args: ['while true; do echo hello world; sleep 30; done;']
