steps:
- name: 'node'
  entrypoint: 'npm'
  args: ['test']
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'us-central1-docker.pkg.dev/$PROJECT_ID/my-repo/hello-world:0.1.0', '.' ]
images:
- 'us-central1-docker.pkg.dev/$PROJECT_ID/my-repo/hello-world:0.1.0'
